import type { MigrationProfile } from "./types.js";

export const vue2ToVue3Profile: MigrationProfile = {
  id: "vue2-to-vue3",
  name: "Vue 2 to Vue 3",
  description: "Migration profile for upgrading from Vue 2 to Vue 3",

  patternRules: [
    {
      id: "filters",
      category: "Template Syntax",
      pattern: /\{\{[^}]*\|[^}]+\}\}/,
      fileGlob: "**/*.{vue,html}",
      severity: "breaking",
      message: "Vue 3 removed filters. Replace with computed properties or method calls.",
    },
    {
      id: "event-bus-on",
      category: "Event Bus",
      pattern: /\$on\s*\(/,
      fileGlob: "**/*.{vue,js,ts}",
      severity: "breaking",
      message: "Vue 3 removed $on. Use an external event emitter library (e.g., mitt).",
    },
    {
      id: "event-bus-off",
      category: "Event Bus",
      pattern: /\$off\s*\(/,
      fileGlob: "**/*.{vue,js,ts}",
      severity: "breaking",
      message: "Vue 3 removed $off. Use an external event emitter library (e.g., mitt).",
    },
    {
      id: "event-bus-once",
      category: "Event Bus",
      pattern: /\$once\s*\(/,
      fileGlob: "**/*.{vue,js,ts}",
      severity: "breaking",
      message: "Vue 3 removed $once. Use an external event emitter library (e.g., mitt).",
    },
    {
      id: "vue-use",
      category: "Global API",
      pattern: /Vue\.use\s*\(/,
      fileGlob: "**/*.{vue,js,ts}",
      severity: "breaking",
      message: "Vue 3 replaced Vue.use() with app.use(). Refactor to use createApp().",
    },
    {
      id: "vue-component",
      category: "Global API",
      pattern: /Vue\.component\s*\(/,
      fileGlob: "**/*.{vue,js,ts}",
      severity: "breaking",
      message: "Vue 3 replaced Vue.component() with app.component().",
    },
    {
      id: "vue-directive",
      category: "Global API",
      pattern: /Vue\.directive\s*\(/,
      fileGlob: "**/*.{vue,js,ts}",
      severity: "breaking",
      message: "Vue 3 replaced Vue.directive() with app.directive().",
    },
    {
      id: "vue-mixin",
      category: "Global API",
      pattern: /Vue\.mixin\s*\(/,
      fileGlob: "**/*.{vue,js,ts}",
      severity: "breaking",
      message: "Vue 3 replaced Vue.mixin() with app.mixin(). Consider Composition API instead.",
    },
    {
      id: "vue-filter",
      category: "Global API",
      pattern: /Vue\.filter\s*\(/,
      fileGlob: "**/*.{vue,js,ts}",
      severity: "breaking",
      message: "Vue 3 removed Vue.filter(). Use computed properties or methods.",
    },
    {
      id: "vue-prototype",
      category: "Global API",
      pattern: /Vue\.prototype\b/,
      fileGlob: "**/*.{vue,js,ts}",
      severity: "breaking",
      message: "Vue 3 replaced Vue.prototype with app.config.globalProperties.",
    },
    {
      id: "set-delete",
      category: "Reactivity",
      pattern: /\$set\s*\(|\$delete\s*\(/,
      fileGlob: "**/*.{vue,js,ts}",
      severity: "deprecated",
      message: "Vue 3 no longer needs $set/$delete. Direct property assignment is reactive.",
    },
    {
      id: "before-destroy",
      category: "Lifecycle",
      pattern: /beforeDestroy\b/,
      fileGlob: "**/*.{vue,js,ts}",
      severity: "breaking",
      message: "Vue 3 renamed beforeDestroy to beforeUnmount.",
    },
    {
      id: "destroyed",
      category: "Lifecycle",
      pattern: /\bdestroyed\s*[:(]/,
      fileGlob: "**/*.{vue,js,ts}",
      severity: "breaking",
      message: "Vue 3 renamed destroyed to unmounted.",
    },
    {
      id: "functional-template",
      category: "Components",
      pattern: /functional\s*>/,
      fileGlob: "**/*.vue",
      severity: "breaking",
      message: "Vue 3 removed functional template syntax. Use plain functions.",
    },
    {
      id: "scoped-slots",
      category: "Slots",
      pattern: /\$scopedSlots\b/,
      fileGlob: "**/*.{vue,js,ts}",
      severity: "breaking",
      message: "Vue 3 unified $scopedSlots into $slots.",
    },
    {
      id: "listeners",
      category: "Attributes",
      pattern: /\$listeners\b/,
      fileGlob: "**/*.{vue,js,ts}",
      severity: "breaking",
      message: "Vue 3 removed $listeners. Listeners are now part of $attrs.",
    },
    {
      id: "children",
      category: "Instance",
      pattern: /\$children\b/,
      fileGlob: "**/*.{vue,js,ts}",
      severity: "breaking",
      message: "Vue 3 removed $children. Use template refs instead.",
    },
    {
      id: "keycode-modifiers",
      category: "Events",
      pattern: /\.(keyCode|keyCodes)\b|@keyup\.\d+/,
      fileGlob: "**/*.{vue,html}",
      severity: "breaking",
      message: "Vue 3 removed numeric keyCode modifiers. Use named key modifiers.",
    },
    {
      id: "native-modifier",
      category: "Events",
      pattern: /\.native\b/,
      fileGlob: "**/*.{vue,html}",
      severity: "breaking",
      message: "Vue 3 removed .native modifier. Use emits option to define component events.",
    },
    {
      id: "data-as-object",
      category: "Options",
      pattern: /data\s*:\s*\{/,
      fileGlob: "**/*.{vue,js,ts}",
      severity: "warning",
      message: "Vue 3 requires data to be a function. Ensure data() returns an object.",
    },
    {
      id: "inline-template",
      category: "Templates",
      pattern: /inline-template\b/,
      fileGlob: "**/*.{vue,html}",
      severity: "breaking",
      message: "Vue 3 removed inline-template attribute.",
    },
  ],

  dependencyRules: [
    {
      name: "vue",
      severity: "breaking",
      message: "Must upgrade vue from v2 to v3.",
    },
    {
      name: "vuex",
      severity: "breaking",
      message: "Vuex 3 (for Vue 2) must be upgraded to Vuex 4, or migrate to Pinia.",
    },
    {
      name: "vue-router",
      severity: "breaking",
      message: "Vue Router 3 (for Vue 2) must be upgraded to Vue Router 4.",
    },
    {
      name: "vue-class-component",
      severity: "breaking",
      message: "vue-class-component v7 is not compatible with Vue 3. Consider migrating to Composition API.",
    },
    {
      name: "vue-property-decorator",
      severity: "breaking",
      message: "vue-property-decorator is not compatible with Vue 3. Migrate to Composition API.",
    },
    {
      name: "@vue/composition-api",
      severity: "deprecated",
      message: "@vue/composition-api is a backport for Vue 2. Remove it when upgrading to Vue 3 (built-in).",
    },
  ],

  researchQueries: [
    {
      label: "Vue 3 Breaking Changes",
      url: "https://v3-migration.vuejs.org/breaking-changes/",
      prompt: "Extract every breaking change listed on this page. For each one, provide: the old Vue 2 API or pattern, what replaces it in Vue 3, and a brief code example showing the migration. Format as a structured list.",
    },
    {
      label: "Vue 3 Ecosystem Compatibility",
      url: "https://v3-migration.vuejs.org/recommendations.html",
      prompt: "List all recommended library upgrades and replacements for migrating from Vue 2 to Vue 3. Include version numbers, alternative libraries (e.g. Vuex vs Pinia), and compatibility notes.",
    },
    {
      label: "Vue 3 Composition API Guide",
      url: "https://vuejs.org/guide/extras/composition-api-faq.html",
      prompt: "Summarize the key differences between Options API and Composition API. List the main patterns developers need to learn: setup(), ref(), reactive(), computed(), watch(), lifecycle hooks. Provide before/after code snippets.",
    },
  ],

  researchKeywords: [
    "breaking change", "deprecated", "removed", "migration",
    "composition api", "options api", "createApp", "defineComponent",
    "setup", "ref", "reactive", "computed", "watch",
    "vuex", "pinia", "vue-router", "vite",
    "filter", "mixin", "directive", "plugin",
    "$on", "$off", "$once", "$set", "$delete",
    "$listeners", "$children", "$scopedSlots",
  ],

  configFilePatterns: ["webpack.config", "vue.config", "vite.config", "nuxt.config"],

  preparationSteps: [
    {
      title: "Create migration branch",
      description: "Create a dedicated branch for the migration work.",
      affectedFiles: [],
      effort: "low",
    },
    {
      title: "Install Vue 3 compatibility build",
      description: "Install @vue/compat to enable incremental migration.",
      affectedFiles: ["package.json"],
      effort: "low",
    },
    {
      title: "Update build configuration",
      description: "Configure bundler to alias vue to @vue/compat.",
      affectedFiles: [],
      effort: "medium",
    },
  ],

  phaseTemplates: [
    {
      name: "Global API & Lifecycle Changes",
      description: "Update global API calls and renamed lifecycle hooks (can be partially automated)",
      categories: ["Global API", "Lifecycle"],
    },
    {
      name: "Manual Breaking Changes",
      description: "Manually refactor patterns that require code restructuring",
      categories: [
        "Template Syntax", "Event Bus", "Slots", "Attributes",
        "Instance", "Events", "Components", "Templates", "Reactivity", "Options",
      ],
    },
  ],

  cleanupSteps: [
    {
      title: "Remove @vue/compat",
      description: "Switch from compatibility build to standard Vue 3.",
      affectedFiles: ["package.json"],
      effort: "medium",
    },
    {
      title: "Run full test suite",
      description: "Execute all tests and fix any remaining failures.",
      affectedFiles: [],
      effort: "medium",
    },
    {
      title: "Production build verification",
      description: "Verify production build completes without errors.",
      affectedFiles: [],
      effort: "low",
    },
  ],
};
